# Generated by Django 5.0.6 on 2025-07-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsdata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Analytics Datum', 'verbose_name_plural': 'Analytics Data'},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='campaignupdate',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AlterModelOptions(
            name='donationtransaction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('can_manage_organization_approvals', 'Can approve/reject organizations')], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.RemoveField(
            model_name='analyticsdata',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='analyticsdata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='core.organization'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization officially managing or endorsing this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaigns_by_org', to='core.organization'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization_approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization_approval_status',
            field=models.CharField(choices=[('Pending Organization Review', 'Pending Organization Review'), ('Approved by Organization', 'Approved by Organization'), ('Rejected by Organization', 'Rejected by Organization'), ('N/A', 'N/A')], default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='requested_organization_for_approval',
            field=models.ForeignKey(blank=True, help_text='If this campaign needs approval from a specific organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_pending_org_approval', to='core.organization'),
        ),
        migrations.AddField(
            model_name='donationtransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='analyticsdata',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='core.campaign'),
        ),
        migrations.AlterField(
            model_name='analyticsdata',
            name='details',
            field=models.JSONField(blank=True, help_text='Store additional event details as JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='analyticsdata',
            name='event_type',
            field=models.CharField(choices=[('Page View', 'Page View'), ('Campaign View', 'Campaign View'), ('Donation Attempt', 'Donation Attempt'), ('Donation Success', 'Donation Success'), ('Login', 'Login'), ('Registration', 'Registration'), ('Campaign Create', 'Campaign Create'), ('Organization Registration', 'Organization Registration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='analyticsdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtransaction',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationtransaction',
            name='donor_name',
            field=models.CharField(blank=True, help_text='Name if not a registered user or anonymous.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donationtransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Comments by site superuser admin regarding approval/rejection.', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_admin',
            field=models.OneToOneField(blank=True, help_text="The user account that manages this organization's panel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Upload a PDF document for verification.', null=True, upload_to='organization_docs/'),
        ),
    ]
