# Generated by Django 5.0.6 on 2025-07-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_analyticsdata_options_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdata',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User-Agent string from the browser.', max_length=255, null=True),
        ),
    ]
